## Purpose

We are going to explore, review and create a report choosing the best mutual funds.

Install HTML5 Lib to do we scraping:

In [24]:
# run this sniped of code: !pip install html5lib

Requirement already satisfied: html5lib in c:\users\st114\anaconda3\lib\site-packages (1.1)
Requirement already satisfied: six>=1.9 in c:\users\st114\anaconda3\lib\site-packages (from html5lib) (1.16.0)
Requirement already satisfied: webencodings in c:\users\st114\anaconda3\lib\site-packages (from html5lib) (0.5.1)

### HTML/Web Scraping: You can aslo Scrape data from HTML tables on webpages

https://finance.yahoo.com/screener/predefined/top_mutual_funds/?offset=0&count=100

In [1]:
import pandas as pd
import numpy as np

# URL of the webpage containing the table
url = 'https://finance.yahoo.com/screener/predefined/top_mutual_funds/?offset=0&count=100'

# Extract all tables from the webpage

tables = pd.read_html(url)
# Print the number of tables found
print(f"Number of tables found: {len(tables)}")

# Access the first table (adjust the index if needed)
data_from_html = tables[0]

# Display the scraped data
print("Data scraped from HTML table:")
print(data_from_html)

# Transform the DataFrame into a CSV file

csv_file_path = 'top_mutual_funds.csv'
data_from_html.to_csv(csv_file_path, index=False)

print(f"Data has been saved to {csv_file_path}")

Number of tables found: 1
Data scraped from HTML table:
   Symbol                                               Name  Change % Change  \
0   RYZCX                            Rydex Precious Metals C    0.74   +2.74%
1   RYPMX                          Rydex Precious Metals Inv    1.02   +2.73%
2   ENPIX                   ProFunds UltraSector Energy Fund    1.16   +2.72%
3   ENPSX                   ProFunds UltraSector Energy Fund    0.98   +2.71%
4   RYMNX                            Rydex Precious Metals A    0.94   +2.71%
5   RYMPX                            Rydex Precious Metals H    0.90   +2.71%
6   FEURX                                First Eagle Gold R6    0.58   +2.22%
7   BIVRX                                 Invenomic Investor    0.37   +2.22%
8   FEGOX                                 First Eagle Gold C    0.50   +2.20%
9   BIVSX                      Invenomic Super Institutional    0.38   +2.19%
10  FEGIX                                 First Eagle Gold I    0.57   +2.19%
11  SGGDX                                 First Eagle Gold A    0.55   +2.18%
12  BIVIX                            Invenomic Institutional    0.37   +2.17%
13  FKRCX                Franklin Gold and Precious Metals A    0.37   +1.98%
14  FRGOX                Franklin Gold and Precious Metals C    0.32   +1.96%
15  FGADX              Franklin Gold and Precious Metals Adv    0.39   +1.92%
16  FGPMX               Franklin Gold and Precious Metals R6    0.39   +1.89%
17  TGUSX  TCW Funds, Inc. - TCW New America Premier Equi...    0.55   +1.76%
18  TIBOX             Thornburg Investment Income Builder R6    0.42   +1.65%
19  TIBIX              Thornburg Investment Income Builder I    0.41   +1.63%
20  TIBMX             Thornburg Investment Income Builder R5    0.41   +1.60%
21  FSENX                   Fidelity Select Energy Portfolio    0.94   +1.57%
22  TIBAX              Thornburg Investment Income Builder A    0.40   +1.57%
23  FAGNX                          Fidelity Advisor Energy M    0.74   +1.57%
24  FIKAX                          Fidelity Advisor Energy Z    0.76   +1.56%

    Price (Intraday)  50 Day Average  200 Day Average 3-Mo Return YTD Return  \
0              27.00           27.81            24.55      40.48%     17.16%
1              37.38           38.47            33.70      40.84%     17.64%
2              42.57           46.04            43.00      12.36%     15.75%
3              36.13           39.11            36.51      12.08%     15.25%
4              34.68           35.69            31.32      40.74%     17.51%
5              33.27           34.24            30.07      40.78%     17.53%
6              26.14           26.85            24.40      26.42%     10.03%
7              16.70           17.92            19.87       3.04%     -7.14%
8              22.75           23.39            21.26      26.15%      9.54%
9              17.34           18.60            20.59       3.16%     -6.99%
10             26.07           26.77            24.33      26.44%     10.02%
11             25.20           25.88            23.52      26.34%      9.90%
12             17.09           18.33            20.31       3.09%     -7.09%
13             18.65           18.89            16.47      39.17%     18.44%
14             16.32           16.54            14.44      38.86%     18.06%
15             20.28           20.53            17.89      39.25%     18.59%
16             20.59           20.83            18.16      39.24%     18.59%
17             31.20           31.78            29.93       0.48%      5.12%
18             25.22           25.17            23.86       7.89%      8.52%
19             25.31           25.25            23.94       7.85%      8.51%
20             25.29           25.23            23.92       7.83%      8.46%
21             59.80           63.15            59.57      10.99%     14.84%
22             25.14           25.06            23.75       7.75%      8.37%
23             47.21           49.89            47.06      10.76%     14.52%
24             48.69           51.41            48.51      10.95%     14.83%

    52 Week Range
0             NaN
1             NaN
2             NaN
3             NaN
4             NaN
5             NaN
6             NaN
7             NaN
8             NaN
9             NaN
10            NaN
11            NaN
12            NaN
13            NaN
14            NaN
15            NaN
16            NaN
17            NaN
18            NaN
19            NaN
20            NaN
21            NaN
22            NaN
23            NaN
24            NaN
Data has been saved to top_mutual_funds.csv

## Step 1 - Import and Inspect the data. 

- what are the data types
- Is the dataset missing data?
- What values are in each column?

In [68]:
import pandas as pd
import numpy as np
df = pd.read_csv("top_mutual_funds.csv")
df.dtypes
df.head()
df.columns = df.columns.str.replace(' ', '_')
df.dtypes
df['%_Change'] = df['%_Change'].str.replace('%', '').astype(float)
df['3-Mo_Return'] = df['3-Mo_Return'].str.replace('%', '').astype(float)
df['YTD_Return'] = df['YTD_Return'].str.replace('%', '').astype(float)
df.head()
df.dtypes

df.info()
df.head()

print("#####Mutual fund analysis Report#################")
#average price(intraday)
mean_intraday = np.mean(df['Price_(Intraday)'].values)
print('This is the average number for intraday price-->', mean_intraday)
#average price for 50 day average
Avg_50day=np.average(df['50_Day_Average'].values)
print('This is the average number for 50day :',Avg_50day )
#standard deviation of the %_Change
std_percent_change=np.std(df['%_Change'].values)
print("This is the standard deviation of the %_Change:", std_percent_change)
#standard deviation of the column change
std_column_change=np.std(df['Change'].values)
print("This is the standard deviation of the Change:", std_column_change)
#sum of the price(intraday) column
sum_price_intraday=np.sum(df['Price_(Intraday)'].values)
print('This is the sum of intraday price:',sum_price_intraday )
#minimum value in column % Change
min_percent_change=np.min(df['%_Change'].values)
print("This is the minimum value in %_Change:",min_percent_change )
#maximum value in column % Change
max_percent_change=np.max(df['%_Change'].values)
print("This is the maximum value in %_Change:",max_percent_change )

#To find top3 mutual funds
df['newly_added_values']=(df['3-Mo_Return'] + df['YTD_Return'].values)
top_3mutual_fund = df.sort_values(by='newly_added_values'  , ascending=False).head(3)
print(top_3mutual_fund)
print("############# Top3 mutual fund #############")
top_3mutual_fund[['Symbol', 'Name', '3-Mo_Return', 'YTD_Return', 'newly_added_values']]
#print("adding 3month return and yearly return values:",top3_mutual_funds)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Symbol            25 non-null     object
 1   Name              25 non-null     object
 2   Change            25 non-null     float64
 3   %_Change          25 non-null     float64
 4   Price_(Intraday)  25 non-null     float64
 5   50_Day_Average    25 non-null     float64
 6   200_Day_Average   25 non-null     float64
 7   3-Mo_Return       25 non-null     float64
 8   YTD_Return        25 non-null     float64
 9   52_Week_Range     0 non-null      float64
dtypes: float64(8), object(2)
memory usage: 2.1+ KB
#####Mutual fund analysis Report#################
This is the average number for intraday price--> 29.0408
This is the average number for 50day : 30.113200000000003
This is the standard deviation of the %_Change: 0.41982853642886164
This is the standard deviation of the Change: 0.24931714742472086
This is the sum of intraday price: 726.02
This is the minimum value in %_Change: 1.56
This is the maximum value in %_Change: 2.74
  Symbol                       Name  Change  %_Change  Price_(Intraday)  \
1  RYPMX  Rydex Precious Metals Inv    1.02      2.73             37.38
5  RYMPX    Rydex Precious Metals H    0.90      2.71             33.27
4  RYMNX    Rydex Precious Metals A    0.94      2.71             34.68

   50_Day_Average  200_Day_Average  3-Mo_Return  YTD_Return  52_Week_Range  \
1           38.47            33.70        40.84       17.64            NaN
5           34.24            30.07        40.78       17.53            NaN
4           35.69            31.32        40.74       17.51            NaN

   newly_added_values
1               58.48
5               58.31
4               58.25
############# Top3 mutual fund #############

,Symbol,Name,3-Mo_Return,YTD_Return,newly_added_values
1,RYPMX,Rydex Precious Metals Inv,40.84,17.64,58.48
5,RYMPX,Rydex Precious Metals H,40.78,17.53,58.31
4,RYMNX,Rydex Precious Metals A,40.74,17.51,58.25

### Observation: The titles have spaces between them, let's fix that

Observations: We can see that there are some columns that need to be changed from objects to floats so we can do some calculations.

- % Change             object
- 3-Mo Return          object
- YTD Return           object

Symbol               object
Name                 object
Change              float64
%_Change             object
Price_(Intraday)    float64
50_Day_Average      float64
200_Day_Average     float64
3-Mo_Return          object
YTD_Return           object
52_Week_Range       float64
dtype: object

## Step 2 - Change variable types if necessary

In [20]:
#df['column'] = df['column'].str.replace('%', '').astype(float)

In [21]:
df.head()

,Symbol,Name,Change,%_Change,Price_(Intraday),50_Day_Average,200_Day_Average,3-Mo_Return,YTD_Return,52_Week_Range
0,RYZCX,Rydex Precious Metals C,0.74,2.74,27.00,27.81,24.55,40.48,17.16,NaN
1,RYPMX,Rydex Precious Metals Inv,1.02,2.73,37.38,38.47,33.70,40.84,17.64,NaN
2,ENPIX,ProFunds UltraSector Energy Fund,1.16,2.72,42.57,46.04,43.00,12.36,15.75,NaN
3,ENPSX,ProFunds UltraSector Energy Fund,0.98,2.71,36.13,39.11,36.51,12.08,15.25,NaN
4,RYMNX,Rydex Precious Metals A,0.94,2.71,34.68,35.69,31.32,40.74,17.51,NaN

### Let's do some exploring of the data

- Using numpy:
    - what is the average price(intraday)?
    - What is the average price for 50 day average?
    - What is the 200 day average?
    - What is the standard deviation of the %_Change?
    - What is the standard deviation of the column change?
    - What is the sum of the price(intraday) column?
    - What is the minimum value in column "% Change"?
    - What is the maximum value in column "% Change"?

## Overall report:
- Based on the what you have learned during our data exploration.
- Which top 3 mutual funds would you choose and why?